### ISSUE TITLE
java version "1.8.0_131"也不支持，

### ISSUE THREAD

**Issue by fenghaichun** [yueshutong/JavaMonitor#6]
java version如下：
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
异常信息如下：
```
---->02 Exception in thread "main" java.lang.reflect.InvocationTargetException
---->03 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
---->04 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
---->05 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
---->06 	at java.lang.reflect.Method.invoke(Method.java:606)
---->07 	at sun.tools.jinfo.JInfo.runTool(JInfo.java:97)
---->08 	at sun.tools.jinfo.JInfo.main(JInfo.java:71)
---->09 Caused by: sun.jvm.hotspot.runtime.VMVersionMismatchException: Supported versions are 24.45-b08. Target VM is 25.131-b11
---->10 	at sun.jvm.hotspot.runtime.VM.checkVMVersion(VM.java:234)
---->11 	at sun.jvm.hotspot.runtime.VM.<init>(VM.java:297)
---->12 	at sun.jvm.hotspot.runtime.VM.initialize(VM.java:368)
---->13 	at sun.jvm.hotspot.bugspot.BugSpotAgent.setupVM(BugSpotAgent.java:598)
---->14 	at sun.jvm.hotspot.bugspot.BugSpotAgent.go(BugSpotAgent.java:493)
---->15 	at sun.jvm.hotspot.bugspot.BugSpotAgent.attach(BugSpotAgent.java:331)
---->16 	at sun.jvm.hotspot.tools.Tool.start(Tool.java:163)
---->17 	at sun.jvm.hotspot.tools.JInfo.main(JInfo.java:128)
---->18 	... 6 more
```

**Comment by yueshutong** [comment]
你是不是配置了多个java环境变量
